name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, buster-latest, stretch, jessie]

    # timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Install mlx dependencies
      run: |
        sudo apt-get install gcc make xorg libxext-dev libbsd-dev
    - name: Install xdotool to simulate inputs (command-line X11 automation tool)
      run: sudo apt install xdotool
    - name: Run ./configure
      run: ./configure
    - name: Run ./run_tests.sh
      run: |
        cd test/
        sh run_tests.sh
    # - name: Run ./run_tests.sh + check leaks
    #   run: |
    #     echo "Info: still reachable report is not considered as a leak.\n   Thus, valgrind will not exit(1) (and it is good in our case)"
    #     valgrind --leak-check=full --error-exitcode=1 ./mlx-test
  


  