name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    # env:
    #   DISPLAY: ':99'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11.0, macos-10.15]

    # timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Install mlx dependencies
      run: |
        sudo apt-get install gcc make xorg libxext-dev libbsd-dev
    - name: Install xdotool to simulate inputs (command-line X11 automation tool)
      run: sudo apt-get install xdotool
    - name: Run ./configure
      run: ./configure
    # - name: Run headless test
    #   uses: GabrielBB/xvfb-action@v1
    #   with:
    #     run: npm test
    # - name: Setup headless environment
    #   run: |
        # sudo apt-get install xvfb
        # export DISPLAY='99.0'
        # Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    # xvfb-maybe electron-mocha ./test/*.js
    # xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    # xvfb-run --auto-servernum npm test
    - name: Run ./run_tests.sh
      run: |
        set -ex
        echo ------------------------- $DISPLAY
        cd test/
        Xvfb :99 -screen 0 1024x768x24 > /dev/null &
        sleep 20
        clang  main_test_x11.c -lXext -lX11 -lm &&  ./a.out
      # sh run_tests.sh
      # xvfb-run --auto-servernum ./run_tests.sh
    # - name: Run ./run_tests.sh + check leaks
    #   run: |
    #     echo "Info: still reachable report is not considered as a leak.\n   Thus, valgrind will not exit(1) (and it is good in our case)"
    #     valgrind --leak-check=full --error-exitcode=1 ./mlx-test
  


  